client:
  base_url: https://api.llm7.io/v1
  api_key: ${LLM7_API_KEY:unused}
  model: gpt-4.1-nano-2025-04-14   # multimodal model (text + image)

run:
  prompt: >
    Briefly describe what is in the image and identify the main subject.
  temperature: 0.0

image:
  # Use either a local file or a remote URL:
  path: ./images/pacman.png
  # url: https://upload.wikimedia.org/wikipedia/commons/9/9a/Pug_600.jpg
